var fullStack=[`digraph G_0 {
style=filled;
color=lightgrey;
node [shape=rectangle];
label="SwiftTarget$SwiftStringRenderer.toString";
fontsize=30;
labelloc=t;
"2" -> "3";
"8" -> "9";
"1" -> "2";
"7" -> "8";
"8" -> "24";
"0" -> "1";
"6" -> "7";
"10" -> "11";
"5" -> "6";
"10" -> "719";
"4" -> "5";
"6" -> "10";
"3" -> "4";
"5" [label="$z0 = virtualinvoke $r1.<java.lang.String: boolean equals(java.lang.Object)>(r0)",shape=cds,tooltip="1.0",penwidth=3.0,color=red,style=filled,fillcolor=khaki1];
"3" [label="r4 := @parameter2: java.util.Locale",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"4" [label="$r1 = \\"javaescape\\"",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"2" [label="r0 := @parameter1: java.lang.String",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"8" [label="$r7 = virtualinvoke $r6.<java.lang.String: java.lang.String replace(java.lang.CharSequence,java.lang.CharSequence)>(\\"\\\\u\\", \\"\\\\u005Cu\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"24" [label="r3 := @this: java.lang.String",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=azure3];
"0" [label="r2 := @this: org.antlr.v4.codegen.target.SwiftTarget$SwiftStringRenderer",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"719" [label="r16 := @this: org.stringtemplate.v4.StringRenderer",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"11" [label="return $r5",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"9" [label="return $r7",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"1" [label="r3 := @parameter0: java.lang.Object",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"10" [label="$r5 = specialinvoke r2.<org.stringtemplate.v4.StringRenderer: java.lang.String toString(java.lang.Object,java.lang.String,java.util.Locale)>(r3, r0, r4)",shape=cds,tooltip="1.0",penwidth=3.0,color=red,style=filled,fillcolor=khaki1];
"6" [label="if $z0 == 0 goto $r5 = specialinvoke r2.<org.stringtemplate.v4.StringRenderer: java.lang.String toString(java.lang.Object,java.lang.String,java.util.Locale)>(r3, r0, r4)",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"7" [label="$r6 = (java.lang.String) r3",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=azure3];
}`,
    `digraph G_7 {
style=filled;
color=lightgrey;
node [shape=rectangle];
label="StringRenderer.toString";
fontsize=30;
labelloc=t;
"750" -> "751";
"721" -> "722";
"750" -> "753";
"736" -> "737";
"742" -> "743";
"728" -> "729";
"734" -> "735";
"737" -> "747";
"740" -> "741";
"755" -> "758";
"759" -> "760";
"726" -> "727";
"755" -> "756";
"732" -> "733";
"719" -> "720";
"747" -> "748";
"724" -> "725";
"727" -> "730";
"746" -> "748";
"753" -> "754";
"730" -> "731";
"745" -> "746";
"750" -> "754";
"722" -> "723";
"751" -> "752";
"737" -> "738";
"743" -> "744";
"720" -> "721";
"758" -> "759";
"735" -> "736";
"741" -> "742";
"727" -> "728";
"756" -> "757";
"754" -> "755";
"731" -> "732";
"735" -> "749";
"760" -> "761";
"731" -> "734";
"749" -> "750";
"724" -> "726";
"723" -> "724";
"739" -> "740";
"738" -> "739";
"751" -> "753";
"744" -> "745";
"724" [label="if r2 != null goto $z0 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"upper\\")",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"745" [label="$r17 = virtualinvoke $r11.<java.lang.StringBuilder: java.lang.String toString()>()",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"754" [label="$z4 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"xmlencode\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"756" [label="$r6 = staticinvoke <org.stringtemplate.v4.StringRenderer: java.lang.String escapeHTML(java.lang.String)>(r1)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"726" [label="$z0 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"upper\\")",shape=cds,tooltip="1.0",penwidth=3.0,color=black,style=filled,fillcolor=lightsalmon];
"752" [label="return $r7",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"723" [label="r1 = (java.lang.String) r0",shape=rectangle,tooltip="1.0",penwidth=1.0,color=red,style=filled,fillcolor=khaki1];
"722" [label="r3 := @parameter2: java.util.Locale",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"731" [label="if $z1 == 0 goto $z2 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"cap\\")",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"753" [label="$r14 := @caughtexception",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"761" [label="return $r5",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"743" [label="$r10 = virtualinvoke r1.<java.lang.String: java.lang.String substring(int)>(1)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"755" [label="if $z4 == 0 goto $r4 = newarray (java.lang.Object)[1]",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"759" [label="$r4[0] = r1",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"740" [label="$c1 = virtualinvoke r1.<java.lang.String: char charAt(int)>(0)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"733" [label="return $r12",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"730" [label="$z1 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"lower\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"748" [label="return $r17",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"757" [label="return $r6",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"735" [label="if $z2 == 0 goto $z3 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"urlencode\\")",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"747" [label="$r17 = r1",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"738" [label="$r8 = new java.lang.StringBuilder",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"746" [label="goto [?= return $r17]",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"736" [label="$i0 = virtualinvoke r1.<java.lang.String: int length()>()",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"734" [label="$z2 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"cap\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"750" [label="if $z3 == 0 goto $z4 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"xmlencode\\")",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"744" [label="$r11 = virtualinvoke $r9.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r10)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"728" [label="$r13 = virtualinvoke r1.<java.lang.String: java.lang.String toUpperCase(java.util.Locale)>(r3)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"751" [label="$r7 = staticinvoke <java.net.URLEncoder: java.lang.String encode(java.lang.String,java.lang.String)>(r1, \\"UTF8\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"719" [label="r16 := @this: org.stringtemplate.v4.StringRenderer",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"725" [label="return r1",shape=circle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"732" [label="$r12 = virtualinvoke r1.<java.lang.String: java.lang.String toLowerCase(java.util.Locale)>(r3)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"741" [label="$c2 = staticinvoke <java.lang.Character: char toUpperCase(char)>($c1)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"727" [label="if $z0 == 0 goto $z1 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"lower\\")",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"749" [label="$z3 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"urlencode\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"729" [label="return $r13",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"758" [label="$r4 = newarray (java.lang.Object)[1]",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"721" [label="r2 := @parameter1: java.lang.String",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"760" [label="$r5 = staticinvoke <java.lang.String: java.lang.String format(java.util.Locale,java.lang.String,java.lang.Object[])>(r3, r2, $r4)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"720" [label="r0 := @parameter0: java.lang.Object",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"739" [label="specialinvoke $r8.<java.lang.StringBuilder: void <init>()>()",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"737" [label="if $i0 <= 0 goto $r17 = r1",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"742" [label="$r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(char)>($c2)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
}`,
    `digraph G_0 {
style=filled;
color=lightgrey;
node [shape=rectangle];
label="SwiftTarget$SwiftStringRenderer.toString";
fontsize=30;
labelloc=t;
"2" -> "3";
"8" -> "9";
"1" -> "2";
"7" -> "8";
"8" -> "24";
"0" -> "1";
"6" -> "7";
"10" -> "11";
"5" -> "6";
"10" -> "719";
"4" -> "5";
"6" -> "10";
"3" -> "4";
"5" [label="$z0 = virtualinvoke $r1.<java.lang.String: boolean equals(java.lang.Object)>(r0)",shape=cds,tooltip="1.0",penwidth=3.0,color=black,style=filled,fillcolor=khaki1];
"3" [label="r4 := @parameter2: java.util.Locale",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=azure3];
"4" [label="$r1 = \\"javaescape\\"",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=azure3];
"2" [label="r0 := @parameter1: java.lang.String",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=azure3];
"8" [label="$r7 = virtualinvoke $r6.<java.lang.String: java.lang.String replace(java.lang.CharSequence,java.lang.CharSequence)>(\\"\\\\u\\", \\"\\\\u005Cu\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"24" [label="r3 := @this: java.lang.String",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=azure3];
"0" [label="r2 := @this: org.antlr.v4.codegen.target.SwiftTarget$SwiftStringRenderer",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=azure3];
"719" [label="r16 := @this: org.stringtemplate.v4.StringRenderer",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"11" [label="return $r5",shape=circle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"9" [label="return $r7",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"1" [label="r3 := @parameter0: java.lang.Object",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=azure3];
"10" [label="$r5 = specialinvoke r2.<org.stringtemplate.v4.StringRenderer: java.lang.String toString(java.lang.Object,java.lang.String,java.util.Locale)>(r3, r0, r4)",shape=cds,tooltip="1.0",penwidth=3.0,color=red,style=filled,fillcolor=khaki1];
"6" [label="if $z0 == 0 goto $r5 = specialinvoke r2.<org.stringtemplate.v4.StringRenderer: java.lang.String toString(java.lang.Object,java.lang.String,java.util.Locale)>(r3, r0, r4)",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"7" [label="$r6 = (java.lang.String) r3",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=azure3];
}`,
]
var fullStackDepth=[0,1,0,]
var fullStackVisibility=["public","public","public",]
var uncompletedStack=[`digraph G_0 {
style=filled;
color=lightgrey;
node [shape=rectangle];
label="SwiftTarget$SwiftStringRenderer.toString";
fontsize=30;
labelloc=t;
"2" -> "3";
"8" -> "9";
"1" -> "2";
"7" -> "8";
"8" -> "24";
"0" -> "1";
"6" -> "7";
"10" -> "11";
"5" -> "6";
"10" -> "719";
"4" -> "5";
"6" -> "10";
"3" -> "4";
"5" [label="$z0 = virtualinvoke $r1.<java.lang.String: boolean equals(java.lang.Object)>(r0)",shape=cds,tooltip="1.0",penwidth=3.0,color=red,style=filled,fillcolor=khaki1];
"3" [label="r4 := @parameter2: java.util.Locale",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"4" [label="$r1 = \\"javaescape\\"",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"2" [label="r0 := @parameter1: java.lang.String",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"8" [label="$r7 = virtualinvoke $r6.<java.lang.String: java.lang.String replace(java.lang.CharSequence,java.lang.CharSequence)>(\\"\\\\u\\", \\"\\\\u005Cu\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"24" [label="r3 := @this: java.lang.String",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=azure3];
"0" [label="r2 := @this: org.antlr.v4.codegen.target.SwiftTarget$SwiftStringRenderer",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"719" [label="r16 := @this: org.stringtemplate.v4.StringRenderer",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"11" [label="return $r5",shape=circle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"9" [label="return $r7",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"1" [label="r3 := @parameter0: java.lang.Object",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"10" [label="$r5 = specialinvoke r2.<org.stringtemplate.v4.StringRenderer: java.lang.String toString(java.lang.Object,java.lang.String,java.util.Locale)>(r3, r0, r4)",shape=cds,tooltip="1.0",penwidth=3.0,color=red,style=filled,fillcolor=khaki1];
"6" [label="if $z0 == 0 goto $r5 = specialinvoke r2.<org.stringtemplate.v4.StringRenderer: java.lang.String toString(java.lang.Object,java.lang.String,java.util.Locale)>(r3, r0, r4)",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"7" [label="$r6 = (java.lang.String) r3",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=azure3];
}`,
]
var uncompletedStackDepth=[0,]
var uncompletedStackVisibility=["public",]
var globalGraph=`digraph GlobalGraph {
style=filled;
color=lightgrey;
node [shape=rectangle];
label="GlobalGraph";fontsize=30;
labelloc=t;
"0" [label="r2 := @this: org.antlr.v4.codegen.target.SwiftTarget$SwiftStringRenderer",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"1" [label="r3 := @parameter0: java.lang.Object",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"2" [label="r0 := @parameter1: java.lang.String",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"3" [label="r4 := @parameter2: java.util.Locale",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"4" [label="$r1 = \\"javaescape\\"",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=azure3];
"5" [label="$z0 = virtualinvoke $r1.<java.lang.String: boolean equals(java.lang.Object)>(r0)",shape=cds,tooltip="1.0",penwidth=3.0,color=red,style=filled,fillcolor=khaki1];
"6" [label="if $z0 == 0 goto $r5 = specialinvoke r2.<org.stringtemplate.v4.StringRenderer: java.lang.String toString(java.lang.Object,java.lang.String,java.util.Locale)>(r3, r0, r4)",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"7" [label="$r6 = (java.lang.String) r3",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=azure3];
"8" [label="$r7 = virtualinvoke $r6.<java.lang.String: java.lang.String replace(java.lang.CharSequence,java.lang.CharSequence)>(\\"\\\\u\\", \\"\\\\u005Cu\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"9" [label="return $r7",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"10" [label="$r5 = specialinvoke r2.<org.stringtemplate.v4.StringRenderer: java.lang.String toString(java.lang.Object,java.lang.String,java.util.Locale)>(r3, r0, r4)",shape=cds,tooltip="1.0",penwidth=3.0,color=red,style=filled,fillcolor=khaki1];
"11" [label="return $r5",shape=circle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"719" [label="r16 := @this: org.stringtemplate.v4.StringRenderer",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"720" [label="r0 := @parameter0: java.lang.Object",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"721" [label="r2 := @parameter1: java.lang.String",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"722" [label="r3 := @parameter2: java.util.Locale",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"723" [label="r1 = (java.lang.String) r0",shape=rectangle,tooltip="1.0",penwidth=1.0,color=red,style=filled,fillcolor=khaki1];
"724" [label="if r2 != null goto $z0 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"upper\\")",shape=rectangle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"725" [label="return r1",shape=circle,tooltip="",penwidth=1.0,color=red,style=filled,fillcolor=white];
"726" [label="$z0 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"upper\\")",shape=cds,tooltip="1.0",penwidth=3.0,color=black,style=filled,fillcolor=lightsalmon];
"727" [label="if $z0 == 0 goto $z1 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"lower\\")",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"728" [label="$r13 = virtualinvoke r1.<java.lang.String: java.lang.String toUpperCase(java.util.Locale)>(r3)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"729" [label="return $r13",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"730" [label="$z1 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"lower\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"731" [label="if $z1 == 0 goto $z2 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"cap\\")",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"732" [label="$r12 = virtualinvoke r1.<java.lang.String: java.lang.String toLowerCase(java.util.Locale)>(r3)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"733" [label="return $r12",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"734" [label="$z2 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"cap\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"735" [label="if $z2 == 0 goto $z3 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"urlencode\\")",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"736" [label="$i0 = virtualinvoke r1.<java.lang.String: int length()>()",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"737" [label="if $i0 <= 0 goto $r17 = r1",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"738" [label="$r8 = new java.lang.StringBuilder",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"739" [label="specialinvoke $r8.<java.lang.StringBuilder: void <init>()>()",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"740" [label="$c1 = virtualinvoke r1.<java.lang.String: char charAt(int)>(0)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"741" [label="$c2 = staticinvoke <java.lang.Character: char toUpperCase(char)>($c1)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"742" [label="$r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(char)>($c2)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"743" [label="$r10 = virtualinvoke r1.<java.lang.String: java.lang.String substring(int)>(1)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"744" [label="$r11 = virtualinvoke $r9.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r10)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"745" [label="$r17 = virtualinvoke $r11.<java.lang.StringBuilder: java.lang.String toString()>()",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"746" [label="goto [?= return $r17]",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"747" [label="$r17 = r1",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"748" [label="return $r17",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"749" [label="$z3 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"urlencode\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"750" [label="if $z3 == 0 goto $z4 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"xmlencode\\")",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"751" [label="$r7 = staticinvoke <java.net.URLEncoder: java.lang.String encode(java.lang.String,java.lang.String)>(r1, \\"UTF8\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"752" [label="return $r7",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"753" [label="$r14 := @caughtexception",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"754" [label="$z4 = virtualinvoke r2.<java.lang.String: boolean equals(java.lang.Object)>(\\"xmlencode\\")",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"755" [label="if $z4 == 0 goto $r4 = newarray (java.lang.Object)[1]",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"756" [label="$r6 = staticinvoke <org.stringtemplate.v4.StringRenderer: java.lang.String escapeHTML(java.lang.String)>(r1)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"757" [label="return $r6",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"758" [label="$r4 = newarray (java.lang.Object)[1]",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"759" [label="$r4[0] = r1",shape=rectangle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"760" [label="$r5 = staticinvoke <java.lang.String: java.lang.String format(java.util.Locale,java.lang.String,java.lang.Object[])>(r3, r2, $r4)",shape=cds,tooltip="",penwidth=3.0,color=black,style=filled,fillcolor=white];
"761" [label="return $r5",shape=circle,tooltip="",penwidth=1.0,color=black,style=filled,fillcolor=white];
"0" -> "1" [label="", color=red];
"1" -> "2" [label="", color=red];
"2" -> "3" [label="", color=red];
"3" -> "4" [label="", color=red];
"4" -> "5" [label="1.0", color=red];
"5" -> "6" [label="", color=red];
"6" -> "7" [label=""];
"6" -> "10" [label="1.0", color=red];
"7" -> "8" [label=""];
"8" -> "9" [label=""];
"10" -> "11" [label="", color=red];
"10" -> "719" [label="", style=dotted];
"719" -> "720" [label="", color=red];
"720" -> "721" [label="", color=red];
"721" -> "722" [label="", color=red];
"722" -> "723" [label="1.0", color=red];
"723" -> "724" [label="", color=red];
"724" -> "725" [label="", color=red];
"724" -> "726" [label="1.0", color=lightsalmon];
"726" -> "727" [label=""];
"727" -> "728" [label=""];
"727" -> "730" [label=""];
"728" -> "729" [label=""];
"730" -> "731" [label=""];
"731" -> "732" [label=""];
"731" -> "734" [label=""];
"732" -> "733" [label=""];
"734" -> "735" [label=""];
"735" -> "736" [label=""];
"735" -> "749" [label=""];
"736" -> "737" [label=""];
"737" -> "738" [label=""];
"737" -> "747" [label=""];
"738" -> "739" [label=""];
"739" -> "740" [label=""];
"740" -> "741" [label=""];
"741" -> "742" [label=""];
"742" -> "743" [label=""];
"743" -> "744" [label=""];
"744" -> "745" [label=""];
"745" -> "746" [label=""];
"746" -> "748" [label=""];
"747" -> "748" [label=""];
"749" -> "750" [label=""];
"750" -> "753" [label=""];
"750" -> "751" [label=""];
"750" -> "754" [label=""];
"751" -> "753" [label=""];
"751" -> "752" [label=""];
"753" -> "754" [label=""];
"754" -> "755" [label=""];
"755" -> "756" [label=""];
"755" -> "758" [label=""];
"756" -> "757" [label=""];
"758" -> "759" [label=""];
"759" -> "760" [label=""];
"760" -> "761" [label=""];
}`