sources:
  - org.utbot.examples.taint.TaintCleanerSimple.source:
      add-to: return
      marks: bad

cleaners:
  - org.utbot.examples.taint.TaintCleanerSimple.cleaner:
      remove-from: arg1
      marks: bad

sinks:
  - org.utbot.examples.taint.TaintCleanerSimple.sink:
      check: arg1
      marks: bad
