#!/bin/bash

# switch to environment JVM as needed
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

TOOL=lib/utbot-junit-contest-1.0.jar

export UTBOT_EXTRA_PARAMS=-Xmx4g
export JAVA_HOME=$JAVA_HOME
$JAVA_HOME/bin/java -cp $TOOL sbst.runtool.Main
