package org.utbot.fuzzer

import mu.KotlinLogging
import org.utbot.framework.plugin.api.UtPrimitiveModel
import org.utbot.framework.plugin.api.util.intClassId
import org.utbot.framework.plugin.api.util.voidClassId
import org.utbot.fuzzer.mutators.NumberRandomMutator
import org.utbot.fuzzer.mutators.RegexStringModelMutator
import org.utbot.fuzzer.mutators.StringRandomMutator
import org.utbot.fuzzer.objects.replaceWithMock
import org.utbot.fuzzer.providers.ArrayModelProvider
import org.utbot.fuzzer.providers.CharToStringModelProvider
import org.utbot.fuzzer.providers.CollectionWithEmptyStatesModelProvider
import org.utbot.fuzzer.providers.ConstantsModelProvider
import org.utbot.fuzzer.providers.EnumModelProvider
import org.utbot.fuzzer.providers.CollectionWithModificationModelProvider
import org.utbot.fuzzer.providers.NumberClassModelProvider
import org.utbot.fuzzer.providers.ObjectModelProvider
import org.utbot.fuzzer.providers.PrimitiveDefaultsModelProvider
import org.utbot.fuzzer.providers.PrimitiveWrapperModelProvider
import org.utbot.fuzzer.providers.PrimitivesModelProvider
import org.utbot.fuzzer.providers.RegexModelProvider
import org.utbot.fuzzer.providers.StringConstantModelProvider
import java.util.*
import java.util.concurrent.atomic.AtomicInteger
import kotlin.random.Random
import org.utbot.fuzzer.providers.DateConstantModelProvider
import org.utbot.fuzzer.providers.PrimitiveRandomModelProvider
import org.utbot.fuzzer.providers.RecursiveModelProvider

private val logger by lazy { KotlinLogging.logger {} }

/**
 * Identifier generator interface for fuzzer model providers.
 *
 * Provides fresh identifiers for generated models.
 *
 * Warning: specific generators are not guaranteed to be thread-safe.
 *
 * @param Id the identifier type (e.g., [Int] for [UtReferenceModel] providers)
 */
interface IdGenerator<Id> {
    /**
     * Create a fresh identifier. Each subsequent call should return a different value.
     *
     * The method is not guaranteed to be thread-safe, unless an implementation makes such a guarantee.
     */
    fun createId(): Id
}

/**
 * Identity preserving identifier generator interface.
 *
 * It allows to optionally save identifiers assigned to specific objects and later get the same identifiers
 * for these objects instead of fresh identifiers. This feature is necessary, for example, to implement reference
 * equality for enum models.
 *
 * Warning: specific generators are not guaranteed to be thread-safe.
 *
 * @param Id the identifier type (e.g., [Int] for [UtReferenceModel] providers)
 */
interface IdentityPreservingIdGenerator<Id> : IdGenerator<Id> {
    /**
     * Return an identifier for a specified non-null object. If an identifier has already been assigned
     * to an object, subsequent calls should return the same identifier for this object.
     *
     * Note: the interface does not specify whether reference equality or regular `equals`/`compareTo` equality
     * will be used to compare objects. Each implementation may provide these guarantees by itself.
     *
     * The method is not guaranteed to be thread-safe, unless an implementation makes such a guarantee.
     */
    fun getOrCreateIdForValue(value: Any): Id
}

/**
 * An identity preserving id generator for fuzzer value providers that returns identifiers of type [Int].
 *
 * When identity-preserving identifier is requested, objects are compared by reference.
 * The generator is not thread-safe.
 *
 * @param lowerBound an integer value so that any generated identifier is strictly greater than it.
 *
 * Warning: when generating [UtReferenceModel] identifiers, no identifier should be equal to zero,
 * as this value is reserved for [UtNullModel]. To guarantee it, [lowerBound] should never be negative.
 * Avoid using custom lower bounds (maybe except fuzzer unit tests), use the predefined default value instead.
 */
class ReferencePreservingIntIdGenerator(lowerBound: Int = DEFAULT_LOWER_BOUND) : IdentityPreservingIdGenerator<Int> {
    private val lastId: AtomicInteger = AtomicInteger(lowerBound)
    private val cache: IdentityHashMap<Any?, Int> = IdentityHashMap()

    override fun getOrCreateIdForValue(value: Any): Int {
        return cache.getOrPut(value) { createId() }
    }

    override fun createId(): Int {
        return lastId.incrementAndGet()
    }

    companion object {
        /**
         * The default lower bound (all generated integer identifiers will be greater than it).
         *
         * It is defined as a large value because all synthetic [UtModel] instances
         * must have greater identifiers than the real models.
         */
        const val DEFAULT_LOWER_BOUND: Int = 1500_000_000
    }
}

/**
 * Generated by fuzzer sequence of values which can be passed into the method.
 */
fun fuzz(description: FuzzedMethodDescription, vararg modelProviders: ModelProvider): Sequence<List<FuzzedValue>> {
    if (modelProviders.isEmpty()) {
        throw IllegalArgumentException("At least one model provider is required")
    }

    val values = List<MutableList<FuzzedValue>>(description.parameters.size) { mutableListOf() }
    modelProviders.forEach { fuzzingProvider ->
        fuzzingProvider.generate(description).forEach { (index, model) ->
            val mock = replaceWithMock(model.model, description.shouldMock)
            values[index].add(FuzzedValue(mock, model.createdBy).apply {
                summary = model.summary
            })
        }
    }
    description.parameters.forEachIndexed { index, classId ->
        val models = values[index]
        if (models.isEmpty()) {
            logger.warn { "There's no models provided classId=$classId. No suitable values are generated for ${description.name}" }
            return emptySequence()
        }
    }
    return CartesianProduct(values, Random(0L)).asSequence()
}

/**
 * Wraps sequence of values, iterates through them and mutates.
 *
 * Mutation when possible is generated after every value of source sequence and then supplies values until it needed.
 * [statistics] should not be updated by this method, but can be changed by caller.
 */
fun <T> Sequence<List<FuzzedValue>>.withMutations(statistics: FuzzerStatistics<T>, description: FuzzedMethodDescription, vararg mutators: ModelMutator) = sequence {
    val fvi = iterator()
    val mutatorList = mutators.toList()
    val random = Random(0L)
    while (fvi.hasNext()) {
        // Takes a value that was generated by model providers and submits it
        yield(fvi.next())
        // Fuzzing can generate values that don't recover new paths.
        // So, fuzzing tries to mutate values on each loop
        // if there are too many attempts to find new paths without mutations.
        yieldMutated(statistics, description, mutatorList, random)
    }
    // try mutations if fuzzer tried all combinations if any seeds are available
    @Suppress("ControlFlowWithEmptyBody")
    while (yieldMutated(statistics, description, mutatorList, random)) {}
}

/**
 * Create a sequence that contains all [defaultValues] plus any value which is found as fuzzing with concrete values.
 *
 * Method is useful for generating some bound values,
 * for example, when for code `array.length > 4` there are 2 values in concrete value: 4 and 5.
 *
 * All values after filtering are cast to [Int].
 */
fun fuzzNumbers(concreteValues: Collection<FuzzedConcreteValue>, vararg defaultValues: Int, filter: (Number) -> Boolean = { true }): Sequence<Int> {
    val description = FuzzedMethodDescription("helper: number fuzzing", voidClassId, listOf(intClassId), concreteValues)
    val fuzzedValues = fuzz(description, ConstantsModelProvider)
        .mapNotNull { ((it.single().model as? UtPrimitiveModel)?.value as? Number) }
        .filter(filter)
        .map { it.toInt() }
    return (defaultValues.asSequence() + fuzzedValues).distinct()
}

/**
 * Creates a model provider from a list of default providers.
 */
fun defaultModelProviders(idGenerator: IdentityPreservingIdGenerator<Int>): ModelProvider {
    return modelProviderForRecursiveCalls(idGenerator, recursionDepth = -1)
        .with(ObjectModelProvider(idGenerator))
        .with(ArrayModelProvider(idGenerator))
        .with(CollectionWithModificationModelProvider(idGenerator))
        .exceptIsInstance<PrimitiveRandomModelProvider>()
        .except(PrimitiveDefaultsModelProvider)
        .with(PrimitivesModelProvider)
}

/**
 * Creates a model provider from a list of providers that we want to use by default in [RecursiveModelProvider]
 */
internal fun modelProviderForRecursiveCalls(idGenerator: IdentityPreservingIdGenerator<Int>, recursionDepth: Int): ModelProvider {
    val nonRecursiveProviders = ModelProvider.of(
        CollectionWithEmptyStatesModelProvider(idGenerator),
        EnumModelProvider(idGenerator),
        DateConstantModelProvider(idGenerator),
        RegexModelProvider,
        StringConstantModelProvider,
        CharToStringModelProvider,
        ConstantsModelProvider,
        PrimitiveRandomModelProvider(Random(0)),
        PrimitiveDefaultsModelProvider,
        PrimitiveWrapperModelProvider,
        NumberClassModelProvider(idGenerator, Random(0)),
    )

    return if (recursionDepth >= 0) {
        nonRecursiveProviders
            .with(ObjectModelProvider(idGenerator, recursionDepth))
            .with(ArrayModelProvider(idGenerator, recursionDepth))
            .with(CollectionWithModificationModelProvider(idGenerator, recursionDepth))
    } else {
        nonRecursiveProviders
    }
}


fun defaultModelMutators(): List<ModelMutator> = listOf(
    StringRandomMutator,
    RegexStringModelMutator,
    NumberRandomMutator,
)

/**
 * Tries to mutate a random value from the seed.
 *
 * Returns `null` if didn't try to do any mutation.
 */
fun <T> mutateRandomValueOrNull(
    statistics: FuzzerStatistics<T>,
    description: FuzzedMethodDescription,
    mutators: List<ModelMutator> = defaultModelMutators(),
    random: Random = Random,
): List<FuzzedValue>? {
    if (mutators.isEmpty()) return null
    val values = statistics.takeIf { it.isNotEmpty() }?.randomValues(random) ?: return null
    var newValues :MutableList<FuzzedValue>? = null
    mutators.asSequence()
        .forEach { mut ->
            mut.mutate(description, values, random).forEach { (index, value) ->
                newValues = (newValues ?: values.toMutableList())
                newValues?.set(index, value)
            }
        }
    return newValues
}

/**
 * Run mutations and yields values into the sequence.
 *
 * Mutations are supplied infinitely until [repeat] returns true. [repeat] is run before mutation.
 *
 * @param statistics coverage-based seed
 * @param description method description
 * @param mutators mutators which are applied to the random value
 * @param random instance that is used to choose random index from the [statistics]
 */
suspend fun <T> SequenceScope<List<FuzzedValue>>.yieldMutated(
    statistics: FuzzerStatistics<T>,
    description: FuzzedMethodDescription,
    mutators: List<ModelMutator>,
    random: Random
) : Boolean {
    mutateRandomValueOrNull(statistics, description, mutators, random)?.let {
        yield(it)
        return true
    }
    return false
}