FROM azul/zulu-openjdk:11.0.15-11.56.19

ARG UTBOT_JAVA_CLI
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /usr/src/

RUN apt-get update \
    && apt-get install -y -q --no-install-recommends \
      wget \
      unzip \
    && rm -rf /var/lib/apt/lists/*

# Install UTBot Java CLI

COPY ${UTBOT_JAVA_CLI} .

RUN UTBOT_JAVA_CLI_PATH="$(find /usr/src -type f -name 'utbot-cli*')" \
    && ln -s "${UTBOT_JAVA_CLI_PATH}" /usr/src/utbot-cli.jar

# Install Kotlin compiler

ENV KOTLIN_COMPILER_VERSION=1.7.0
ENV KOTLIN_HOME="/opt/kotlin/kotlinc"

RUN wget --no-verbose https://github.com/JetBrains/kotlin/releases/download/v${KOTLIN_COMPILER_VERSION}/kotlin-compiler-${KOTLIN_COMPILER_VERSION}.zip -O /tmp/${KOTLIN_COMPILER_VERSION}.zip \
    && unzip -q -d /opt/kotlin /tmp/${KOTLIN_COMPILER_VERSION}.zip

ENV PATH="${KOTLIN_HOME}/bin:${PATH}"
