FROM openjdk:8

ARG JAVA_CLI

WORKDIR /usr/src/

# Install UTBot Java CLI

COPY ${JAVA_CLI} .
    
RUN JAVA_CLI_PATH="$(find /usr/src -type f -name 'utbot-cli*')" \
    && ln -s "${JAVA_CLI_PATH}" /usr/src/utbot-cli.jar
