FROM azul/zulu-openjdk:11.0.15-11.56.19

ARG UTBOT_JS_CLI

WORKDIR /usr/src/

# Install UTBot Javascript CLI

COPY ${UTBOT_JS_CLI} .

RUN apt-get update && \
	apt-get install -y curl && \
	
	# Install Node.js
	curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh && \
	/bin/sh nodesource_setup.sh && \
	apt-get install -y nodejs && \
	
	apt-get clean

RUN UTBOT_JS_CLI_PATH="$(find /usr/src -type f -name 'utbot-cli*')" \
    && ln -s "${UTBOT_JS_CLI_PATH}" /usr/src/utbot-cli.jar
