FROM azul/zulu-openjdk:11.0.15-11.56.19

ARG UTBOT_GO_CLI

WORKDIR /usr/src/

# Install UTBot Go CLI

COPY ${UTBOT_GO_CLI} .

RUN apt-get update && \
	apt-get install -y wget && \
	
	# Install Go
	wget  https://go.dev/dl/go1.19.linux-amd64.tar.gz && \
	tar -xvf go1.19.linux-amd64.tar.gz && \
	mv go /usr/local && \
	rm go1.19.linux-amd64.tar.gz && \
	
	apt-get clean

ENV GOROOT /usr/local/go
ENV PATH $GOPATH/bin:$GOROOT/bin:$PATH

RUN UTBOT_GO_CLI_PATH="$(find /usr/src -type f -name 'utbot-cli*')" \
    && ln -s "${UTBOT_GO_CLI_PATH}" /usr/src/utbot-cli.jar
