package org.utbot.framework.util

import org.utbot.framework.plugin.api.ExecutableId
import org.utbot.framework.plugin.api.util.isData
import org.utbot.framework.plugin.api.util.isEnum

fun isKnownSyntheticMethod(method: ExecutableId): Boolean {
    if (method.classId.isEnum)
        return method.name in KnownSyntheticMethodNames.enumSyntheticMethodNames

    if (method.classId.isData)
        return KnownSyntheticMethodNames.dataClassSyntheticMethodNames.any { it.matches(method.name) }

    return false
}

/**
 * Contains names of methods that are always autogenerated and thus it is unlikely that
 * one would want to generate tests for them.
 */
private object KnownSyntheticMethodNames {
    /** List with names of enum methods that are autogenerated */
    val enumSyntheticMethodNames = listOf("values", "valueOf")

    /** List with names of data classes methods that are autogenerated in Kotlin */
    val dataClassSyntheticMethodNames = listOf(
        "equals",
        "hashCode",
        "toString",
        "copy",
        "copy\\\$default",
        "component[1-9][0-9]*"
    ).map { it.toRegex() }
}