/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for AwaitPrimary AST Node type
  * by the ASTNode.java.ftl template
  */
package org.parsers.python.ast;

import org.parsers.python.*;
import static org.parsers.python.PythonConstants.TokenType.*;
@SuppressWarnings("unused")
public class AwaitPrimary extends BaseNode {
}
