/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for BADNAME Token subclass
  * by the ASTToken.java.ftl template
  */
package org.parsers.python.ast;

import org.parsers.python.*;
import org.parsers.python.PythonConstants.TokenType;
import static org.parsers.python.PythonConstants.TokenType.*;
@SuppressWarnings("unused")
public class BADNAME extends Token {
    public BADNAME(TokenType type, PythonLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
