/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for MaybeSequencePattern AST Node type
  * by the ASTNode.java.ftl template
  */
package org.parsers.python.ast;

import org.parsers.python.*;
import static org.parsers.python.PythonConstants.TokenType.*;
public class MaybeSequencePattern extends BaseNode {
}
