/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for Whitespace Token subclass
  * by the ASTToken.java.ftl template
  */
package org.parsers.python.ast;

import org.parsers.python.*;
import org.parsers.python.PythonConstants.TokenType;
import static org.parsers.python.PythonConstants.TokenType.*;
public class Whitespace extends Token {
    public Whitespace(TokenType type, PythonLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
