name: Run diKTat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  diktat_check:
    runs-on: ubuntu-20.04

    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: gradle
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: |
            --continue
            diktatCheck
            -Pdiktat.githubActions=true
      - name: Copy SARIF reports into a single directory
        if: ${{ always() }}
        run: |
          mkdir -p build/diktat-sarif-reports
          i=0
          find -path '*/build/reports/diktat/*.sarif' | while read -r f; do cp "$f" "build/diktat-sarif-reports/diktat-$((i++)).sarif"; done
      - name: Upload SARIF reports to GitHub
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/diktat-sarif-reports
