name: "UTBot Java: night statistics monitoring"

permissions: read-all

on:
   schedule:
     - cron: '0 0 * * *'

jobs:
  run_monitoring:
    uses: ./.github/workflows/collect-statistics.yml
    secrets: inherit
    with:
      runners: 3
      run_number: 1
      message_prefix: night-monitoring
      push_results: true
      send_to_grafana: true
